In [3]:
import numpy as np
import pandas as pd

In [4]:
data = pd.read_csv("E:/Unifield-internship/Project/Pizza Sales Dashboard/pizza_sales.csv")
data.head()

order_details_id  order_id       pizza_id  quantity  order_date order_time  \
0                 1         1     hawaiian_m         1  01-01-2015   11:38:36   
1                 2         2  classic_dlx_m         1  01-01-2015   11:57:40   
2                 3         2  five_cheese_l         1  01-01-2015   11:57:40   
3                 4         2    ital_supr_l         1  01-01-2015   11:57:40   
4                 5         2     mexicana_m         1  01-01-2015   11:57:40   

   unit_price  total_price pizza_size pizza_category  \
0       13.25        13.25          M        Classic   
1       16.00        16.00          M        Classic   
2       18.50        18.50          L         Veggie   
3       20.75        20.75          L        Supreme   
4       16.00        16.00          M         Veggie   

                                   pizza_ingredients  \
0           Sliced Ham, Pineapple, Mozzarella Cheese   
1  Pepperoni, Mushrooms, Red Onions, Red Peppers,...   
2  Mozzarella Cheese, Provolone Cheese, Smoked Go...   
3  Calabrese Salami, Capocollo, Tomatoes, Red Oni...   
4  Tomatoes, Red Peppers, Jalapeno Peppers, Red O...   

                  pizza_name  
0         The Hawaiian Pizza  
1   The Classic Deluxe Pizza  
2      The Five Cheese Pizza  
3  The Italian Supreme Pizza  
4         The Mexicana Pizza

In [5]:
data.isnull().sum()

order_details_id     0
order_id             0
pizza_id             0
quantity             0
order_date           0
order_time           0
unit_price           0
total_price          0
pizza_size           0
pizza_category       0
pizza_ingredients    0
pizza_name           0
dtype: int64

In [6]:
data['quantity'].unique()

array([1, 2, 3, 4], dtype=int64)

In [7]:
data['order_date'].value_counts()

order_date
11/26/2015    261
11/27/2015    259
10/15/2015    258
07-04-2015    233
07-03-2015    207
             ... 
12/27/2015     87
11/22/2015     82
12/29/2015     77
3/22/2015      76
12/30/2015     73
Name: count, Length: 358, dtype: int64

In [8]:
data['order_time'].unique()

array(['11:38:36', '11:57:40', '12:12:28', ..., '20:51:07', '21:14:37',
       '22:09:54'], dtype=object)

In [9]:
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...  
48615    False
48616    False
48617    False
48618    False
48619    False
Length: 48620, dtype: bool

In [10]:
type('order_date')

str

In [16]:
data['order_date'] = pd.to_datetime(data['order_time'])

In [17]:
data['year'] = data['order_date'].dt.year
data['month'] = data['order_date'].dt.month
data['day'] = data['order_date'].dt.day

In [13]:
type('order_time')

str

In [14]:
data['order_time'] = pd.to_datetime(data['order_time'])

data['hour'] = data['order_time'].dt.hour
data['minute'] = data['order_time'].dt.minute
data['second'] = data['order_time'].dt.second

C:\Users\DHRUV\AppData\Local\Temp\ipykernel_1696\2375601171.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['order_time'] = pd.to_datetime(data['order_time'])


In [18]:
data.head()

order_details_id  order_id       pizza_id  quantity          order_date  \
0                 1         1     hawaiian_m         1 2025-03-14 11:38:36   
1                 2         2  classic_dlx_m         1 2025-03-14 11:57:40   
2                 3         2  five_cheese_l         1 2025-03-14 11:57:40   
3                 4         2    ital_supr_l         1 2025-03-14 11:57:40   
4                 5         2     mexicana_m         1 2025-03-14 11:57:40   

           order_time  unit_price  total_price pizza_size pizza_category  \
0 2025-03-14 11:38:36       13.25        13.25          M        Classic   
1 2025-03-14 11:57:40       16.00        16.00          M        Classic   
2 2025-03-14 11:57:40       18.50        18.50          L         Veggie   
3 2025-03-14 11:57:40       20.75        20.75          L        Supreme   
4 2025-03-14 11:57:40       16.00        16.00          M         Veggie   

                                   pizza_ingredients  \
0           Sliced Ham, Pineapple, Mozzarella Cheese   
1  Pepperoni, Mushrooms, Red Onions, Red Peppers,...   
2  Mozzarella Cheese, Provolone Cheese, Smoked Go...   
3  Calabrese Salami, Capocollo, Tomatoes, Red Oni...   
4  Tomatoes, Red Peppers, Jalapeno Peppers, Red O...   

                  pizza_name  hour  minute  second  year  month  day  
0         The Hawaiian Pizza    11      38      36  2025      3   14  
1   The Classic Deluxe Pizza    11      57      40  2025      3   14  
2      The Five Cheese Pizza    11      57      40  2025      3   14  
3  The Italian Supreme Pizza    11      57      40  2025      3   14  
4         The Mexicana Pizza    11      57      40  2025      3   14

In [19]:
data['month'].unique()

array([3])

In [20]:
data['hour'].unique()

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 10,  9])

In [21]:
data['minute'].unique()

array([38, 57, 12, 16, 21, 29, 50, 51, 52,  0,  2,  4, 11, 14, 33, 34, 53,
       59,  3, 19, 23, 44, 54, 35, 41, 32, 56,  7, 15, 28, 55, 25, 26, 48,
        1, 10, 30, 40,  5,  8, 47, 58, 22, 45, 13, 17, 18, 46, 27, 36, 31,
       42, 49,  9, 43, 37, 20, 24, 39,  6])

In [22]:
for x in data['second'].unique():
    if x > 60:
        print(x)
    
else:
    print("There is no valuse in x greater then 60.")
        

There is no valuse in x greater then 60.


In [23]:
drop_col = ['order_date','order_time']

new_data = data.drop(columns = drop_col)

new_data.head()

order_details_id  order_id       pizza_id  quantity  unit_price  \
0                 1         1     hawaiian_m         1       13.25   
1                 2         2  classic_dlx_m         1       16.00   
2                 3         2  five_cheese_l         1       18.50   
3                 4         2    ital_supr_l         1       20.75   
4                 5         2     mexicana_m         1       16.00   

   total_price pizza_size pizza_category  \
0        13.25          M        Classic   
1        16.00          M        Classic   
2        18.50          L         Veggie   
3        20.75          L        Supreme   
4        16.00          M         Veggie   

                                   pizza_ingredients  \
0           Sliced Ham, Pineapple, Mozzarella Cheese   
1  Pepperoni, Mushrooms, Red Onions, Red Peppers,...   
2  Mozzarella Cheese, Provolone Cheese, Smoked Go...   
3  Calabrese Salami, Capocollo, Tomatoes, Red Oni...   
4  Tomatoes, Red Peppers, Jalapeno Peppers, Red O...   

                  pizza_name  hour  minute  second  year  month  day  
0         The Hawaiian Pizza    11      38      36  2025      3   14  
1   The Classic Deluxe Pizza    11      57      40  2025      3   14  
2      The Five Cheese Pizza    11      57      40  2025      3   14  
3  The Italian Supreme Pizza    11      57      40  2025      3   14  
4         The Mexicana Pizza    11      57      40  2025      3   14

In [ ]:
new_data.to_csv('E:/Unifield-internship/Pizza_order.csv', index = True)